class_name CardEnums

enum Element { TWIG, PEBBLE, LEAF, DROPLET }

enum Sage { CEDAR, GRAVEL, PORELLA, TORRENT }

enum ItemType { ATTACK, UTILITY, INSTANT }

enum AbilityAction {
	COLLECT_GOLD,
	DEAL_DAMAGE,
	REDUCE_DAMAGE,
	MOVE_TO_DISCARD_FROM_FIELD,
	MOVE_TO_FIELD_FROM_DISCARD,
	SWAP_FIELD_POSITION,
	DRAW,
	MOVE_TO_HAND_FROM_DISCARD,
	MOVE_TO_DISCARD_FROM_HAND,
	MOVE_TO_HAND_FROM_FIELD,
	MOVE_TO_FIELD_FROM_HAND,
	ADD_SHIELD,
	ADD_BOOST,
	DONT_REMOVE_SHIELD,
	DONT_REMOVE_BOOST,
	REMOVE_ALL_DAMAGE,
	REMOVE_ALL_BOOSTS_AND_SHIELDS,
	REDIRECT_DAMAGE_TO_SELF,
	NEGATE_DAMAGE,
}

enum Team { SELF, ENEMY }

enum AbilityTrigger {
	DAYBREAK,
	ON_PLAY,
	ON_ATTACK,
	ON_MELEE_ATTACK,
	ON_RANGED_ATTACK,
	ON_DAMAGE_DEALT,
	ON_DEFEAT_ENEMY,
	ON_SHIELD_ADDED,
	ON_SHIELD_REMOVED,
	ON_MELEE_ATTACKED,
	ON_RANGED_ATTACKED,
	ON_ATTACKED,
	ON_ENTER_ROW,
	ON_ALLY_ENTER_FORMATION,
	ON_ALLY_LEAVE_FORMATION,
	ON_DEFEATED,
	ON_DAMAGE_ABOUT_TO_BE_DEALT_TO_ALLY,
}

enum TargetScope {
	NONE,
	SELF,
	SELF_SAGE,
	ENEMY_SAGE,
	ROW,
	FORMATION,
	DISCARD_PILE,
	HAND,
	ATTACKING_ELEMENTAL,
	## "N rows away" (Far Strike, Farsight Frenzy, Primitive Strike,
	## Projectile Blast) -- target.rows[0] holds N, the distance counted
	## along the whole board through the attacker's own rows and into the
	## opponent's, not a fixed row number. Resolved in
	## TargetResolver._rows_away_candidates().
	ROWS_AWAY,
}

enum TargetSelection { ALL, CHOOSE_N }

enum AmountSource { FIXED, ATTACKER_STRENGTH, SELF_DAMAGE_COUNT, SELF_SHIELD_COUNT, DISCARDED_COUNT }

enum ConditionStat { BOOST_COUNT, SHIELD_COUNT, DAMAGE_COUNT, GOLD, HAND_SIZE }

enum Comparator { EQUAL, GREATER_OR_EQUAL, LESS_OR_EQUAL, GREATER_THAN, LESS_THAN }

enum AttackType { MELEE, RANGED }
