class_name CardEnums

enum Element { TWIG, PEBBLE, LEAF, DROPLET }

enum Sage { CEDAR, GRAVEL, PORELLA, TORRENT }

enum ItemType { ATTACK, UTILITY, INSTANT }

enum AbilityAction {
	COLLECT_GOLD,
	DEAL_DAMAGE,
	REDUCE_DAMAGE,
	MOVE_TO_DISCARD_FROM_FIELD,
	MOVE_TO_FIELD_FROM_DISCARD,
	SWAP_FIELD_POSITION,
	DRAW,
	MOVE_TO_HAND_FROM_DISCARD,
	MOVE_TO_DISCARD_FROM_HAND,
	MOVE_TO_HAND_FROM_FIELD,
	MOVE_TO_FIELD_FROM_HAND,
	ADD_SHIELD,
	ADD_BOOST,
	DONT_REMOVE_SHIELD,
	DONT_REMOVE_BOOST,
	REMOVE_ALL_DAMAGE,
}

enum Team { SELF, ENEMY }
